files:
  included:
    # - plugins/**/*.rb
  excluded:
    - app/channels/application_cable/channel.rb
    - app/controllers/application_controller.rb
    - app/mailers/application_mailer.rb
    - app/models/application_record.rb
    - app/jobs/application_job.rb
