sudo: required

cache: bundler

services:
  - docker

before_install:
  - sudo service postgresql stop
  # Wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - cp .env.example .env
  - docker-compose run api bundle exec rake db:create db:migrate

script:
  - docker-compose run api bundle exec rake test
  - docker-compose run api bundle exec rspec spec --format documentation
