sudo: required

language: ruby

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose run api bundle exec rake db:create db:migrate

script:
  - docker-compose run api bundle exec rake test
