version: '3.1'

services:
  api:
    build: .
    command: bundle exec foreman start -f Procfile.dev
    volumes:
      - .:/rails-graphql-api
    ports:
      - 3000:3000
      - 8808:8808
    depends_on:
      - redis
      - db
    env_file:
      - .env

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis:4.0-alpine
    command: redis-server
    ports:
      - 6379:6379
