version: '3.1'

services:
  api:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/rails-graphql-api
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
