development:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: rails-graphql-api_dev
  # adapter: async

test:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: rails-graphql-api_test
  # adapter: test

production:
  adapter: redis
  url: redis://redis:6379/0
  channel_prefix: rails-graphql-api_production
